# Generated by Django 2.1.5 on 2021-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20211122_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
